enable-magisk-update = false # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

[YouTube-Morphe]
build-mode = "apk"
exclusive-patches = true
included-patches = "'Hide ads' 'Remove background playback restrictions' 'Navigation bar' 'Video ads' 'Sanitize sharing links' 'SponsorBlock' 'Bypass URL redirects' 'Open links externally' 'Spoof video streams'"
excluded-patches = ""
version = "auto"
dpi = "480-640dpi"
arch = "arm64-v8a"
patches-version = "dev"
apkmirror_cf-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"

[GooglePhotos]
build-mode = "apk"
force-build = true
version = "latest"
patches-version = "latest"
patches-source = "RookieEnough/De-Vanced"
cli-source = "MorpheApp/morphe-cli"
dpi = "480-640dpi"
arch = "arm64-v8a"
apkmirror_cf-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"

[Music-Morphe]
build-mode = "apk"
exclusive-patches = true
included-patches = "'Bypass certificate checks' 'Enable exclusive audio playback' 'Hide ads' 'Hide music video ads' 'Sanitize sharing links' 'Spoof video streams' 'Remove background playback restrictions'"
excluded-patches = ""
version = "auto"
patches-version = "dev"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
arch = "arm64-v8a"
dpi = "480-640dpi"
apkmirror_cf-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
