enable-magisk-update = true
parallel-jobs = 1

[Music-Extended]
enabled = true
app-name = "Music"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
arch = "arm64-v8a"
excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music' 'Enable debug logging' 
version = "auto"
patches-version = "latest"
integrations-version = "latest"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"

[YouTube-Extended]
enabled = true
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Enable debug logging'"
version = "latest"
patches-version = "latest"
integrations-version = "latest"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
