enable-magisk-update = false # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube-Morphe]
build-mode = "apk"
exclusive-patches = true
included-patches = "'Hide ads' 'Remove background playback restrictions' 'Navigation bar' 'Video ads' 'Sanitize sharing links' 'SponsorBlock' 'Bypass URL redirects' 'Open links externally' 'Spoof video streams'"
excluded-patches = ""
version = "21.28.204"
arch = "arm64-v8a"
patches-version = "dev"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"

[GooglePhotos]
build-mode = "apk"
force-build = true
version = "7.84.0.949657053"
patches-version = "latest"
patches-source = "RookieEnough/De-Vanced"
cli-source = "MorpheApp/morphe-cli"
arch = "arm64-v8a"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

[Music-Morphe]
build-mode = "apk"
exclusive-patches = true
included-patches = "'Bypass certificate checks' 'Enable exclusive audio playback' 'Hide ads' 'Hide music video ads' 'Sanitize sharing links' 'Spoof video streams' 'Remove background playback restrictions'"
excluded-patches = ""
version = "9.28.51"
patches-version = "dev"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
arch = "arm64-v8a"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
